#!/usr/bin/env python3
import py_compile
import os

# We get the file name of the pythpne script from the envuronment variable
pyfile = os.environ.get("PYFILE")
# Here, we compile the script and generate the output filename
pycfile = pyfile + "c"
py_compile.compile(pyfile,pycfile)

#Output the status of the message and then exit
print(f"Compiling {pyfile} ...")
