#!/usr/bin/env python3
import py_compile
import os

pyfile = os.environ.get('PYFILE')

if pyfile is None:
	exit(1)

	print(f"Compiling {pyfile} ...")

try:
	py_compile.compile(pyfile, cfile=f"{pyfile}c")
except py_compile.PyCompileError as e:
	print(e.msg, file = sys.stderr)
	exit(1)
