#!/bin/bash
# We get the file name of the pythpne script from the envuronment variable
pyfile=$PYFILE

# Compile the python script and generate the output filename
pycfile=${pyfile}c
python -m py_compile $pyfile

#Output the status message and exit
echo "Compiling $pyfile ..."
